### ISSUE TITLE
Support Visual Studio 2015 ARM for Win10 Mobile

### ISSUE THREAD

**Issue by JimSEOW** [rageappliedgame/EmotionDetectionAsset#1]
Could you please provide (if possible .NET) wrapper that compile to VS2015 ARM for W10M? [We are discussing](https://github.com/accord-net/framework/issues/652) if we could integrate your work into accord-NET

**Comment by wvdvegt** [comment]
The code depends on dlib for some of the basic detection operations (face detection & landmarks). If dlib works on ARM porting may be possible.
